### ISSUE TITLE
Can you explain the installation steps of building and compiling?

### ISSUE THREAD

**Issue by kinger2023** [ByPumbaa/Warthog#1]
Can you explain the installation steps of building and compiling? Thank you

**Comment by ByPumbaa** [comment]
1. Install gcc, meson, ninja: `# apt install meson ninja-build build-essential`
2. Clone the repo `git clone https://github.com/ByPumbaa/Warthog`
3. cd the repo `cd Warthog`
4. Create build directory `meson build .`
5. cd into build directory `cd build`
6. Compile using ninja `ninja`

**Comment by makertronic** [comment]
on ubuntu 22 here is how i do : 
![image](https://github.com/ByPumbaa/Warthog/assets/85033212/5f2b8303-cbee-465a-b373-4675cfe9775b)
