### ISSUE TITLE
Please how can I fix this terrible problem

### ISSUE THREAD

**Issue by kinger2023** [ByPumbaa/Warthog#3]
After rebuilding and compiling, the startup still fails, and the following error is prompted

meirong@OS-20230306EWPM:~/youzhu/new/build/src$ cd wallet
meirong@OS-20230306EWPM:~/youzhu/new/build/src/wallet$ ls -a
.  ..  wart-wallet  wart-wallet.p
meirong@OS-20230306EWPM:~/youzhu/new/build/src/wallet$ ./wart-wallet
./wart-wallet: symbol lookup error: ./wart-wallet: undefined symbol: secp256k1_ecdsa_recover

meirong@OS-20230306EWPM:~/youzhu/new/build/src/wallet$ ldd wart-wallet
        linux-vdso.so.1 (0x00007fffcf86b000)
        libsecp256k1.so => /usr/local/lib/libsecp256k1.so (0x00007fb2c4f72000)
        libuv.so.1 => /home/meirong/youzhu/new/build/src/wallet/./../../subprojects/libuv-v1.44.2/libuv.so.1 (0x00007fb2c4f2f000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb2c4d00000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb2c4ce0000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb2c4cbd000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb2c4ab0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb2c4aa0000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb2c4951000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb2c529e000)

**Comment by ByPumbaa** [comment]
We fixed it, please try again after downloading the newest warthog code and recompiling.
